# Generated by Django 4.2.11 on 2025-09-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='Emprestimos',
        ),
    ]
