# Generated by Django 4.2.11 on 2025-09-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_ativo'),
        ('livro', '0008_rename_emprestimo_emprestimos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='nome_emprestado_anonimo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='nome_emprestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
