# Generated by Django 4.2.11 on 2025-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_emprestimos_nome_emprestado_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
