# Generated by Django 4.2.11 on 2025-09-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
